language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - coverity_scan

notifications:
  email:
    recipients:
      - troels.bentsen@nordea.com
    on_success: never
    on_failure: always

env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "DhqM82TzUguFAz8qyAX3AnFgSPZ5KQuNbHRZrapgCQUPyMXd25zHidhBPm4pxyYgrHyAKPDjOiSASNKQ7XVcdBj0c5cSpjQJHiukgH54r+GUvy8UsXGDRyp15oUeM13stxodvNEovc4+CBjHfWS9683jaU7wd3cGfZSs7N2P8azTqFvghEmkBlhXJeaVS1fBZEUtp1pwH1I1vTOvp5HR+8lblXgo7McJlC9h5Md8brhToXe5jAmisAE9m5i8ZlUzhU51RDwUf8RLPWvlR6/6lJaEpNpiN0cF30NvfIl2/cnR5TbBmOtAXmqcwwvm6alnooiKmeDO4EzdgeB5W7p61g864HmP/tiW3iNt93HT5phjZWaR+Hmlp7UwsoxX7PmriRnfywrTnqjzpb6BtpE10gsA3C+DsqnzvfIRIyS/+3TjHfdwVssv25jxm8lc+N9Yw01HusLFqwIeBxd7R5IsTURwLxIZgIQ0FbSXVDPLdPGyKHV4peB8SM27v6ADZ2cbDvGlSu1xlr+1K9yuia5xreTeowSWhwnYuI5Yyk9liWVj34KHB/Y2Uajk0lDsdq42n6MW0KVWl7p7FJenQNgp+vdj2UoLSnP0IhX43+RMpZGX5GfvyYggwG4w93MAk0tYtdk00jIyk2wagDUflljwIIJj1ikgmlrlNAkJkDNemW0="

   # OSSRH_USER
   #- secure: "gld2tGJfjyykfKZHqBKzdDWvlsrf+67qrAY8CiGtk5yCiSatrrz0xnrBNDzbtLKv1ym5Ju1Tb99jikdtvR1w7cvKcXmV1HR+lzHJwygBJApjAu8tiyQAb9ZaT/0NtgLFh4m8DGz28ZnV9G7xPVR+hFV9My9hgEdcWnyLKAvQUdkfDhzGDeG5D3f4aqIhEqfhydBXkObl2/u8JARSV5EF59lASdGf4R2/yVmQUv5WaUVJOUm+S76+fu+4tgdKNAEG2F/lsIPxwf2R4GbobAwWsy+bBB62sVsTkQkKgVSq6bkpyVFvTvw5fzH/PaOpxG2P1zoYNMVk37tYAjmPzkdM+Yx6t37RP5iT4i24RnOhuFEsFmGyF8nQo5P7/UOKa8sy3J5OQvuABUpVNnNrx2qFkzKzyDspn2pZvq6t+CBAurWcid2PsDftrflg5JAhDw7iw/UoPl3ZNh2Ka/O7mTBcHCHHWhxSlXgSva1neHi/SgThiMa1QlTUFkKxt6C4ozQcu5zLLuW4G8KahGJhenmKu0L595oedvO1UGa+SD3M+u8wQ1IxZpw6vgdyj/pTWBSz+8QW38qsy6SxwnQgsAjFO3OEb2NRP6Y0LVpEhugmACRabWlxPQWGlxjPC3pch+HMThtVC+LSO/omGacS024YPWWrCRLl3L7vDlftqlfIeuM="
   # OSSRH_PASS
   #- secure: "IJCSu150rHzWtv6o5+aoaG2l1jmWAzM3D/ngpfwmumGsS2aeD1SdzWMwrMl4MYzdDko/NBPMo7gfvphKhrY4buD2gWu7WLEs4aM1vcI9hA32QHG/PEVidxWWQdr5nwxlfdEgFqU/Nr5r1PGhvaqAbARPaAFexy4TJNxOvDDbM6jJo3cy26lwW8j7WQ26h966jGt7KzQ9XWfyRVT/+b8xVp4SSm6Lc60J4zs+Y4qNObjNExBJyKbw/J2bTANVULSobPiYE5QcsDDBxwT/9q82K9f7WqY3WTpszBnQLyw/nYow6vm7JjnRzdWmnA4Y/XeVvtCKk+nWfVgrXFYZqsM8MgvXx8TmWGJ+bQY+Y4cEfrmV9o5fHlzMPCGECluSYhwUkPun71SH+kAuRBNT1SWdOkRqyWSaShWriMDwAs6ZU0GqDeD38aOYp4pxD0G+lGGvQenayBfxPa4Ef6oKTVitdCtLRgLraRVzBIiKTMFK/ArUmeiPj3fTNvh0sKb7T0c7t0PrJjEKz5I4hWYjPp9noeU1peaxj8d9Ki+Epve4Gz5I9imryVVgXpy+JXgJaxltDKdojZKRsePA03d44NxMTShWMOeVvYFtjNbCYdf671BYmYZusUUc3Ldsvqv8+f7OP/j9PdJGeS4egXuKHbYyk9em+AqMPQh6PakosjiF+aI="

before_install:
  - 'echo ${TRAVIS_TAG} - ${TRAVIS_PULL_REQUEST} - ${TRAVIS_BUILD_NUMBER}'
  - 'if [ -z "${TRAVIS_TAG}" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then ./set_snapshot_version.sh; fi'

after_success:
  - 'echo Done building'
  - 'if [ -z "${TRAVIS_TAG}" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn deploy -DskipTests --settings travis-deploy.xml; fi'

addons:
  coverity_scan:
    project:
      name: "NordeaOSS/copybook4java"
      description: "Build submitted via Travis CI"
    notification_email: troels.bentsen@nordea.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan